//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS.ST.BHC.BSP.PDC.ExcelClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BBS.ST.BHC.BSP.PDC.ExcelClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Retrieve Chemical Data.
        /// </summary>
        internal static string Action_AdvancedCompoundInfo_Caption {
            get {
                return ResourceManager.GetString("Action_AdvancedCompoundInfo_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format as &amp;BAY-No..
        /// </summary>
        internal static string Action_CI_Format_BAY {
            get {
                return ResourceManager.GetString("Action_CI_Format_BAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Verify Compound List.
        /// </summary>
        internal static string Action_CI_Format_Caption {
            get {
                return ResourceManager.GetString("Action_CI_Format_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format as CO&amp;P-No..
        /// </summary>
        internal static string Action_CI_Format_COP {
            get {
                return ResourceManager.GetString("Action_CI_Format_COP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format as &amp;COS-No..
        /// </summary>
        internal static string Action_CI_Format_COS {
            get {
                return ResourceManager.GetString("Action_CI_Format_COS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format as &amp;ZK-No..
        /// </summary>
        internal static string Action_CI_Format_ZK {
            get {
                return ResourceManager.GetString("Action_CI_Format_ZK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve &amp;Formula.
        /// </summary>
        internal static string Action_CI_Formula_Caption {
            get {
                return ResourceManager.GetString("Action_CI_Formula_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;etrieve Prep No.
        /// </summary>
        internal static string Action_CI_Prepno_Caption {
            get {
                return ResourceManager.GetString("Action_CI_Prepno_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve &amp;Structure Formula.
        /// </summary>
        internal static string Action_CI_Structure_Caption {
            get {
                return ResourceManager.GetString("Action_CI_Structure_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve &amp;Molecular Weight.
        /// </summary>
        internal static string Action_CI_WEIGHT_Caption {
            get {
                return ResourceManager.GetString("Action_CI_WEIGHT_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear.
        /// </summary>
        internal static string Action_ClearData_BarTitle {
            get {
                return ResourceManager.GetString("Action_ClearData_BarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear &amp;Worksheet.
        /// </summary>
        internal static string Action_ClearData_Caption {
            get {
                return ResourceManager.GetString("Action_ClearData_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Retrieve Chemical Data.
        /// </summary>
        internal static string Action_CompoundInfo_Caption {
            get {
                return ResourceManager.GetString("Action_CompoundInfo_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create &amp;new PDC Worksheet.
        /// </summary>
        internal static string Action_CreateWorkbook_Caption {
            get {
                return ResourceManager.GetString("Action_CreateWorkbook_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete Data from PDC Database.
        /// </summary>
        internal static string Action_Delete_Caption {
            get {
                return ResourceManager.GetString("Action_Delete_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC &amp;Login.
        /// </summary>
        internal static string Action_Login_Caption {
            get {
                return ResourceManager.GetString("Action_Login_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC &amp;Logout.
        /// </summary>
        internal static string Action_Logout_Caption {
            get {
                return ResourceManager.GetString("Action_Logout_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve &amp;measurement level data.
        /// </summary>
        internal static string Action_RetrieveMeasurementLevelData_Caption {
            get {
                return ResourceManager.GetString("Action_RetrieveMeasurementLevelData_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search.
        /// </summary>
        internal static string Action_SearchTestdata_BarTitle {
            get {
                return ResourceManager.GetString("Action_SearchTestdata_BarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search Test Data.
        /// </summary>
        internal static string Action_SearchTestData_Caption {
            get {
                return ResourceManager.GetString("Action_SearchTestData_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling worksheet.
        /// </summary>
        internal static string Action_SearchTestData_Filling_Caption {
            get {
                return ResourceManager.GetString("Action_SearchTestData_Filling_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Structure format.
        /// </summary>
        internal static string Action_StructureFormat_Caption {
            get {
                return ResourceManager.GetString("Action_StructureFormat_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Commit Changes to PDC Database.
        /// </summary>
        internal static string Action_Update_Caption {
            get {
                return ResourceManager.GetString("Action_Update_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Upload Worksheet to PDC Database.
        /// </summary>
        internal static string Action_Upload_Workbook {
            get {
                return ResourceManager.GetString("Action_Upload_Workbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Upload.
        /// </summary>
        internal static string Action_UploadWorkbook_BarTitle {
            get {
                return ResourceManager.GetString("Action_UploadWorkbook_BarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Validate Worksheet.
        /// </summary>
        internal static string Action_Validate_Caption {
            get {
                return ResourceManager.GetString("Action_Validate_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Info.
        /// </summary>
        internal static string Action_VersionInfo_Caption {
            get {
                return ResourceManager.GetString("Action_VersionInfo_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC W&amp;indows Login.
        /// </summary>
        internal static string Action_WinLogin_Caption {
            get {
                return ResourceManager.GetString("Action_WinLogin_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; not found. Get missing file!.
        /// </summary>
        internal static string ATOMCOLOR_FILE_MISSING {
            get {
                return ResourceManager.GetString("ATOMCOLOR_FILE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC.
        /// </summary>
        internal static string CI_Contextmenu_Caption {
            get {
                return ResourceManager.GetString("CI_Contextmenu_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Date.
        /// </summary>
        internal static string COL_HEADER_DATE_RESULT {
            get {
                return ResourceManager.GetString("COL_HEADER_DATE_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string Header_Column {
            get {
                return ResourceManager.GetString("Header_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Header_Message {
            get {
                return ResourceManager.GetString("Header_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string Header_Row {
            get {
                return ResourceManager.GetString("Header_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severness.
        /// </summary>
        internal static string Header_Severness {
            get {
                return ResourceManager.GetString("Header_Severness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testname.
        /// </summary>
        internal static string Header_Testname {
            get {
                return ResourceManager.GetString("Header_Testname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testno.
        /// </summary>
        internal static string Header_Testno {
            get {
                return ResourceManager.GetString("Header_Testno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Header_Version {
            get {
                return ResourceManager.GetString("Header_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Deleting {0} rows..
        /// </summary>
        internal static string LABEL_DELETE_DATA {
            get {
                return ResourceManager.GetString("LABEL_DELETE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Loading measurements for selected testdata.
        /// </summary>
        internal static string LABEL_LOAD_MEASUREMENTS {
            get {
                return ResourceManager.GetString("LABEL_LOAD_MEASUREMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Looking up the compound information.
        /// </summary>
        internal static string LABEL_LOOKUP_COMPOUND_INFO {
            get {
                return ResourceManager.GetString("LABEL_LOOKUP_COMPOUND_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Searching for testdata.
        /// </summary>
        internal static string LABEL_SEARCH_TESTDATA {
            get {
                return ResourceManager.GetString("LABEL_SEARCH_TESTDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Updating selected testdata.
        /// </summary>
        internal static string LABEL_UPDATE {
            get {
                return ResourceManager.GetString("LABEL_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Uploading testdata.
        /// </summary>
        internal static string LABEL_UPLOAD_WORKBOOK {
            get {
                return ResourceManager.GetString("LABEL_UPLOAD_WORKBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Validating workbook.
        /// </summary>
        internal static string LABEL_VALIDATE_WORKBOOK {
            get {
                return ResourceManager.GetString("LABEL_VALIDATE_WORKBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column {0} is mandatory or differentiating and must not be deleted, since it has no default value..
        /// </summary>
        internal static string LIST_MANDATORY_DIFF_COLUMN_DELETED {
            get {
                return ResourceManager.GetString("LIST_MANDATORY_DIFF_COLUMN_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column {0} is the connection to the measurements and should not be deleted.
        /// </summary>
        internal static string LIST_MEASUREMENT_COLUMN_DELETED {
            get {
                return ResourceManager.GetString("LIST_MEASUREMENT_COLUMN_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column {0} is needed by PDC  and must not be deleted.
        /// </summary>
        internal static string LIST_NEEDED_PDC_COLUMN_DELETED {
            get {
                return ResourceManager.GetString("LIST_NEEDED_PDC_COLUMN_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action {0} is currently disabled..
        /// </summary>
        internal static string MSG_ACTION_NOT_ENABLED {
            get {
                return ResourceManager.GetString("MSG_ACTION_NOT_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action {0} not found..
        /// </summary>
        internal static string MSG_ACTION_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_ACTION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected hidden rows. Therefore it&apos;s not allowed to delete data. 
        ///
        ///Probably this happened as you have filtered data. 
        ///Unfilter the sheet and try again..
        /// </summary>
        internal static string MSG_AUTO_FILTER_SET_DELETE {
            get {
                return ResourceManager.GetString("MSG_AUTO_FILTER_SET_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected hidden rows. Therefore it&apos;s not allowed to update data. 
        ///    
        ///Probably this happened as you have filtered data. 
        ///Unfilter the sheet and try again..
        /// </summary>
        internal static string MSG_AUTO_FILTER_SET_UPDATE {
            get {
                return ResourceManager.GetString("MSG_AUTO_FILTER_SET_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not allowed to set a filter before uploading data. Please remove the filter..
        /// </summary>
        internal static string MSG_AUTO_FILTER_SET_UPLOAD {
            get {
                return ResourceManager.GetString("MSG_AUTO_FILTER_SET_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Autoupdate.
        /// </summary>
        internal static string MSG_AUTOUPDATE_TITLE {
            get {
                return ResourceManager.GetString("MSG_AUTOUPDATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The studies already exist in PDC:
        ///    
        ///Experimentlevelparameter:
        ///{0}
        ///
        ///Should the data be replaced/updated? .
        /// </summary>
        internal static string MSG_AUTOUPDATE_VALUES {
            get {
                return ResourceManager.GetString("MSG_AUTOUPDATE_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel is in cellediting mode. Finish cellediting before executing this operation.
        /// </summary>
        internal static string MSG_CELLEDITINGMODE_TEXT {
            get {
                return ResourceManager.GetString("MSG_CELLEDITINGMODE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Cannot execute operation.
        /// </summary>
        internal static string MSG_CELLEDITINGMODE_TITLE {
            get {
                return ResourceManager.GetString("MSG_CELLEDITINGMODE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart EXCEL for proper Data Handling..
        /// </summary>
        internal static string MSG_COMException_Restart {
            get {
                return ResourceManager.GetString("MSG_COMException_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: An exception occured in Excel.
        /// </summary>
        internal static string MSG_COMException_Title {
            get {
                return ResourceManager.GetString("MSG_COMException_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Chemical Data.
        /// </summary>
        internal static string MSG_CompoundInfo_TITLE {
            get {
                return ResourceManager.GetString("MSG_CompoundInfo_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected area is not empty. Proceed?.
        /// </summary>
        internal static string MSG_CompoundInfoOverride_Text {
            get {
                return ResourceManager.GetString("MSG_CompoundInfoOverride_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} rows?.
        /// </summary>
        internal static string MSG_CONFIRM_DELETE_DATA {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_DELETE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to load measurements for {0} rows?.
        /// </summary>
        internal static string MSG_CONFIRM_LOAD_MEASUREMENT_DATA {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_LOAD_MEASUREMENT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Confirm.
        /// </summary>
        internal static string MSG_CONFIRM_TITLE {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update {0} rows?.
        /// </summary>
        internal static string MSG_CONFIRM_UPDATE_DATA {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_UPDATE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Do you really want to save the selected experiments without measurements?.
        /// </summary>
        internal static string MSG_CONFIRM_UPDATE_WITHOUT_MEASUREMENTS {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_UPDATE_WITHOUT_MEASUREMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter cwid and password.
        /// </summary>
        internal static string MSG_CWID_PWD_MISSING {
            get {
                return ResourceManager.GetString("MSG_CWID_PWD_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An old  PDC-Workbook {0} is invalid.
        ///Should the marker as PDC-Workbook be removed?
        ///That would mean, the Workbook will not be recognized as PDC-Workbook anymore..
        /// </summary>
        internal static string MSG_DESERIALIZATION_WORKBOOK_TEXT {
            get {
                return ResourceManager.GetString("MSG_DESERIALIZATION_WORKBOOK_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Deserialization Error.
        /// </summary>
        internal static string MSG_DESERIALIZATION_WORKBOOK_TITLE {
            get {
                return ResourceManager.GetString("MSG_DESERIALIZATION_WORKBOOK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout: PDC has reached the predefined limit for waiting on a response from the server. Your upload data will be processed normally, but your client will not receive any transfer status information for this upload.
        ///Please check your data using the PDC client after 1 day. In addition you can check your upload report in the PDC Portal.
        ///To change the timeout limit of your PDC client or receive further information please contact your service desk. The PDC team will gladly consult and assist you..
        /// </summary>
        internal static string MSG_ERROR_TIMEOUT {
            get {
                return ResourceManager.GetString("MSG_ERROR_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Error.
        /// </summary>
        internal static string MSG_ERROR_TITLE {
            get {
                return ResourceManager.GetString("MSG_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add the confidential image. Error message was written to the log file..
        /// </summary>
        internal static string MSG_FAILED_TO_ADD_SECRET_PIC_TEXT {
            get {
                return ResourceManager.GetString("MSG_FAILED_TO_ADD_SECRET_PIC_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidential Image.
        /// </summary>
        internal static string MSG_FAILED_TO_ADD_SECRET_PIC_TITLE {
            get {
                return ResourceManager.GetString("MSG_FAILED_TO_ADD_SECRET_PIC_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: An exception occured.
        /// </summary>
        internal static string MSG_GeneralException_Title {
            get {
                return ResourceManager.GetString("MSG_GeneralException_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected hidden rows. It&apos;s not allowed to delete hidden rows..
        /// </summary>
        internal static string MSG_HIDDEN_ROWS_SELECTED {
            get {
                return ResourceManager.GetString("MSG_HIDDEN_ROWS_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Info.
        /// </summary>
        internal static string MSG_INFO_TITLE {
            get {
                return ResourceManager.GetString("MSG_INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid number.
        /// </summary>
        internal static string MSG_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("MSG_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using a workbook, which once have had PDC-Sheets.
        ///Some references have been found and removed to avoid crashs.
        ///
        ///Please save the workbook..
        /// </summary>
        internal static string MSG_INVALID_WORKBOOK_DEFINED_NAME_DELTED {
            get {
                return ResourceManager.GetString("MSG_INVALID_WORKBOOK_DEFINED_NAME_DELTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Load Measurements.
        /// </summary>
        internal static string MSG_LOAD_MEASUREMENTS_TITLE {
            get {
                return ResourceManager.GetString("MSG_LOAD_MEASUREMENTS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Login was successful.
        /// </summary>
        internal static string MSG_LOGIN_TEXT {
            get {
                return ResourceManager.GetString("MSG_LOGIN_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Login.
        /// </summary>
        internal static string MSG_LOGIN_TITLE {
            get {
                return ResourceManager.GetString("MSG_LOGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Measurement data error.
        /// </summary>
        internal static string MSG_MeasurementException_Title {
            get {
                return ResourceManager.GetString("MSG_MeasurementException_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no selected cells.
        /// </summary>
        internal static string MSG_NO_CELLS_SELECTED {
            get {
                return ResourceManager.GetString("MSG_NO_CELLS_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of Prepno, Structure, MW of MF must be selected.
        /// </summary>
        internal static string MSG_NO_COMPOUNDINFO_SELECTED {
            get {
                return ResourceManager.GetString("MSG_NO_COMPOUNDINFO_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No upload data found.
        /// </summary>
        internal static string MSG_NO_DATA_TO_UPLOAD_TEXT {
            get {
                return ResourceManager.GetString("MSG_NO_DATA_TO_UPLOAD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data for validation found.
        /// </summary>
        internal static string MSG_NO_DATA_TO_VALIDATE_TEXT {
            get {
                return ResourceManager.GetString("MSG_NO_DATA_TO_VALIDATE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Entries found. Change Query conditions?.
        /// </summary>
        internal static string MSG_NO_ENTRIES_FOUND_TEXT {
            get {
                return ResourceManager.GetString("MSG_NO_ENTRIES_FOUND_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The necessary experimentno row was deleted..
        /// </summary>
        internal static string MSG_NO_EXPERIMENTNO_ROW {
            get {
                return ResourceManager.GetString("MSG_NO_EXPERIMENTNO_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The active worksheet is not a PDC worksheet. The action {0} can not be executed..
        /// </summary>
        internal static string MSG_NO_PDC_SHEET {
            get {
                return ResourceManager.GetString("MSG_NO_PDC_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Search conditions selected.
        /// </summary>
        internal static string MSG_NO_SEARCH_CONDITIONS_TEXT {
            get {
                return ResourceManager.GetString("MSG_NO_SEARCH_CONDITIONS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active sheet is not a worksheet.
        /// </summary>
        internal static string MSG_NO_WORKSHEET_TEXT {
            get {
                return ResourceManager.GetString("MSG_NO_WORKSHEET_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not logged in. The action {0} can not be executed..
        /// </summary>
        internal static string MSG_NOT_LOGGED_IN {
            get {
                return ResourceManager.GetString("MSG_NOT_LOGGED_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between {0} and {1}.
        /// </summary>
        internal static string MSG_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("MSG_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Structure Format Dialog: Conflict with target cells.
        /// </summary>
        internal static string MSG_OVERLAP {
            get {
                return ResourceManager.GetString("MSG_OVERLAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not writable. Updates will not work. Please contact your administrator..
        /// </summary>
        internal static string MSG_PATH_NO_WRITABLE {
            get {
                return ResourceManager.GetString("MSG_PATH_NO_WRITABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC server and client version are not equal..
        /// </summary>
        internal static string MSG_PDCVERSION_FAILED {
            get {
                return ResourceManager.GetString("MSG_PDCVERSION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDCVersion.
        /// </summary>
        internal static string MSG_PDCVERSION_TITLE {
            get {
                return ResourceManager.GetString("MSG_PDCVERSION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Do you want to save the changes you made to &apos;{0}&apos;?.
        /// </summary>
        internal static string MSG_SAVE_WORKBOOK_TEXT {
            get {
                return ResourceManager.GetString("MSG_SAVE_WORKBOOK_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel.
        /// </summary>
        internal static string MSG_SAVE_WORKBOOK_TITLE {
            get {
                return ResourceManager.GetString("MSG_SAVE_WORKBOOK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} entries. Display result?.
        /// </summary>
        internal static string MSG_SEARCH_RESULT_TEXT {
            get {
                return ResourceManager.GetString("MSG_SEARCH_RESULT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Search.
        /// </summary>
        internal static string MSG_SEARCH_TITLE {
            get {
                return ResourceManager.GetString("MSG_SEARCH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One sheet is missing. Please create a new PDC working sheet..
        /// </summary>
        internal static string MSG_SHEET_IS_MISSING_TEXT {
            get {
                return ResourceManager.GetString("MSG_SHEET_IS_MISSING_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Missing sheet.
        /// </summary>
        internal static string MSG_SHEET_IS_MISSING_TITLE {
            get {
                return ResourceManager.GetString("MSG_SHEET_IS_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sheet or object with the name {0} already exists (of type {1}).
        /// </summary>
        internal static string MSG_SHEET_NAME_EXISTS_TEXT {
            get {
                return ResourceManager.GetString("MSG_SHEET_NAME_EXISTS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Duplicate sheet name.
        /// </summary>
        internal static string MSG_SHEET_NAME_EXISTS_TITLE {
            get {
                return ResourceManager.GetString("MSG_SHEET_NAME_EXISTS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute operation since the sheet is protected.
        /// </summary>
        internal static string MSG_SHEET_PROTECTED_TEXT {
            get {
                return ResourceManager.GetString("MSG_SHEET_PROTECTED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Sheet protected.
        /// </summary>
        internal static string MSG_SHEET_PROTECTED_TITLE {
            get {
                return ResourceManager.GetString("MSG_SHEET_PROTECTED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test is already open.
        /// </summary>
        internal static string MSG_TEST_ALREADY_OPEN_TEXT {
            get {
                return ResourceManager.GetString("MSG_TEST_ALREADY_OPEN_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Test already open.
        /// </summary>
        internal static string MSG_TEST_ALREADY_OPEN_TITLE {
            get {
                return ResourceManager.GetString("MSG_TEST_ALREADY_OPEN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again with fewer search parameters or update rows..
        /// </summary>
        internal static string MSG_TOO_MANY_SEARCH_PARAMS_TEXT {
            get {
                return ResourceManager.GetString("MSG_TOO_MANY_SEARCH_PARAMS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many Parameters for search or update.
        /// </summary>
        internal static string MSG_TOO_MANY_SEARCH_PARAMS_TITLE {
            get {
                return ResourceManager.GetString("MSG_TOO_MANY_SEARCH_PARAMS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testdata updated..
        /// </summary>
        internal static string MSG_UPDATE_OK_TEXT {
            get {
                return ResourceManager.GetString("MSG_UPDATE_OK_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Testdata update.
        /// </summary>
        internal static string MSG_UPDATE_OK_TITLE {
            get {
                return ResourceManager.GetString("MSG_UPDATE_OK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more records have been deleted from the database. Please retrieve the current data..
        /// </summary>
        internal static string MSG_UPDATE_RECORDS_DELETED {
            get {
                return ResourceManager.GetString("MSG_UPDATE_RECORDS_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Commit changes.
        /// </summary>
        internal static string MSG_UPDATE_TITLE {
            get {
                return ResourceManager.GetString("MSG_UPDATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test data was not uploaded..
        /// </summary>
        internal static string MSG_UPLOAD_FAILED_TEXT {
            get {
                return ResourceManager.GetString("MSG_UPLOAD_FAILED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testdata uploaded.
        ///{0} row(s) and {1} measurement(s)..
        /// </summary>
        internal static string MSG_UPLOAD_OK_TEXT {
            get {
                return ResourceManager.GetString("MSG_UPLOAD_OK_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Testdata upload.
        /// </summary>
        internal static string MSG_UPLOAD_OK_TITLE {
            get {
                return ResourceManager.GetString("MSG_UPLOAD_OK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Upload.
        /// </summary>
        internal static string MSG_UPLOAD_TITLE {
            get {
                return ResourceManager.GetString("MSG_UPLOAD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User aborted action..
        /// </summary>
        internal static string MSG_USER_ABORTED_ACTION {
            get {
                return ResourceManager.GetString("MSG_USER_ABORTED_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Validation.
        /// </summary>
        internal static string MSG_VALIDATE_TITLE {
            get {
                return ResourceManager.GetString("MSG_VALIDATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed..
        /// </summary>
        internal static string MSG_VALIDATION_FAILED {
            get {
                return ResourceManager.GetString("MSG_VALIDATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Versioninfo.
        /// </summary>
        internal static string MSG_VERSIONINFO_TITLE {
            get {
                return ResourceManager.GetString("MSG_VERSIONINFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-Only.
        /// </summary>
        internal static string PRIVILEGE_READ_ONLY {
            get {
                return ResourceManager.GetString("PRIVILEGE_READ_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string PRIVILEGE_UPLOAD {
            get {
                return ResourceManager.GetString("PRIVILEGE_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDC: Structure Format - Validation.
        /// </summary>
        internal static string StructureFormatValidation_Title {
            get {
                return ResourceManager.GetString("StructureFormatValidation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} could not be found.
        /// </summary>
        internal static string VALIDATOR_BINARY_NOT_FOUND {
            get {
                return ResourceManager.GetString("VALIDATOR_BINARY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} is too large for upload. (File has {1} bytes. Maximum is {2}).
        /// </summary>
        internal static string VALIDATOR_BINARY_TOO_LARGE {
            get {
                return ResourceManager.GetString("VALIDATOR_BINARY_TOO_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompoundNo is missing.
        /// </summary>
        internal static string VALIDATOR_COMPOUND_INFO_MISSING {
            get {
                return ResourceManager.GetString("VALIDATOR_COMPOUND_INFO_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one derived result must be present.
        /// </summary>
        internal static string VALIDATOR_DERIVED_MISSING {
            get {
                return ResourceManager.GetString("VALIDATOR_DERIVED_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differentiating parameter must not be empty.
        /// </summary>
        internal static string VALIDATOR_DIFFERENTIATING {
            get {
                return ResourceManager.GetString("VALIDATOR_DIFFERENTIATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory field must not be empty.
        /// </summary>
        internal static string VALIDATOR_MANDATORY {
            get {
                return ResourceManager.GetString("VALIDATOR_MANDATORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert {0} into a numeric value.
        /// </summary>
        internal static string VALIDATOR_NUMERIC_CONVERSION {
            get {
                return ResourceManager.GetString("VALIDATOR_NUMERIC_CONVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreparationNo is missing.
        /// </summary>
        internal static string VALIDATOR_PREPNO_MISSING {
            get {
                return ResourceManager.GetString("VALIDATOR_PREPNO_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the file {0} is not supported ({1}).
        /// </summary>
        internal static string VALIDATOR_UNKNOWN_FILE_TYPE {
            get {
                return ResourceManager.GetString("VALIDATOR_UNKNOWN_FILE_TYPE", resourceCulture);
            }
        }
    }
}
