//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BBS.ST.BHC.BSP.PDC.Lib.WsCustomerManagement {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsCustomerManagementSoapBinding", Namespace="http://by-ws-ics-customermanagement/ws_customermanagement")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RoleProperty))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CustomerProperty))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CustomerCostcenter))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Principal))]
    public partial class WsCustomerManagementService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAuthenticationOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAuthorizationOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustomerInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustomerInfoLDAPOperationCompleted;
        
        private System.Threading.SendOrPostCallback updatePropertiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateRolePropertiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHRDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchCustomersOperationCompleted;
        
        private System.Threading.SendOrPostCallback createCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback addRoleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsCustomerManagementService() {
            this.Url = global::BBS.ST.BHC.BSP.PDC.Lib.Properties.Settings.Default.WsCustomerManagement_URL;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getVersionCompletedEventHandler getVersionCompleted;
        
        /// <remarks/>
        public event getAuthenticationCompletedEventHandler getAuthenticationCompleted;
        
        /// <remarks/>
        public event getAuthorizationCompletedEventHandler getAuthorizationCompleted;
        
        /// <remarks/>
        public event getCustomerInfoCompletedEventHandler getCustomerInfoCompleted;
        
        /// <remarks/>
        public event getCustomerInfoLDAPCompletedEventHandler getCustomerInfoLDAPCompleted;
        
        /// <remarks/>
        public event updatePropertiesCompletedEventHandler updatePropertiesCompleted;
        
        /// <remarks/>
        public event updateRolePropertiesCompletedEventHandler updateRolePropertiesCompleted;
        
        /// <remarks/>
        public event getHRDataCompletedEventHandler getHRDataCompleted;
        
        /// <remarks/>
        public event searchCustomersCompletedEventHandler searchCustomersCompleted;
        
        /// <remarks/>
        public event createCustomerCompletedEventHandler createCustomerCompleted;
        
        /// <remarks/>
        public event addRoleCompletedEventHandler addRoleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://by-ws-ics-customermanagement/ws_customermanagement", ResponseNamespace="http://by-ws-ics-customermanagement/ws_customermanagement")]
        [return: System.Xml.Serialization.SoapElementAttribute("getVersionReturn")]
        public string getVersion() {
            object[] results = this.Invoke("getVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getVersionAsync() {
            this.getVersionAsync(null);
        }
        
        /// <remarks/>
        public void getVersionAsync(object userState) {
            if ((this.getVersionOperationCompleted == null)) {
                this.getVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVersionOperationCompleted);
            }
            this.InvokeAsync("getVersion", new object[0], this.getVersionOperationCompleted, userState);
        }
        
        private void OngetVersionOperationCompleted(object arg) {
            if ((this.getVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVersionCompleted(this, new getVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://by-ws-ics-customermanagement/ws_customermanagement", ResponseNamespace="http://by-ws-ics-customermanagement/ws_customermanagement")]
        [return: System.Xml.Serialization.SoapElementAttribute("getAuthenticationReturn")]
        public Principal[] getAuthentication(string in0, string in1) {
            object[] results = this.Invoke("getAuthentication", new object[] {
                        in0,
                        in1});
            return ((Principal[])(results[0]));
        }
        
        /// <remarks/>
        public void getAuthenticationAsync(string in0, string in1) {
            this.getAuthenticationAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void getAuthenticationAsync(string in0, string in1, object userState) {
            if ((this.getAuthenticationOperationCompleted == null)) {
                this.getAuthenticationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAuthenticationOperationCompleted);
            }
            this.InvokeAsync("getAuthentication", new object[] {
                        in0,
                        in1}, this.getAuthenticationOperationCompleted, userState);
        }
        
        private void OngetAuthenticationOperationCompleted(object arg) {
            if ((this.getAuthenticationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAuthenticationCompleted(this, new getAuthenticationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://by-ws-ics-customermanagement/ws_customermanagement", ResponseNamespace="http://by-ws-ics-customermanagement/ws_customermanagement")]
        [return: System.Xml.Serialization.SoapElementAttribute("getAuthorizationReturn")]
        public Customer getAuthorization(string in0, string in1, string[] in2) {
            object[] results = this.Invoke("getAuthorization", new object[] {
                        in0,
                        in1,
                        in2});
            return ((Customer)(results[0]));
        }
        
        /// <remarks/>
        public void getAuthorizationAsync(string in0, string in1, string[] in2) {
            this.getAuthorizationAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void getAuthorizationAsync(string in0, string in1, string[] in2, object userState) {
            if ((this.getAuthorizationOperationCompleted == null)) {
                this.getAuthorizationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAuthorizationOperationCompleted);
            }
            this.InvokeAsync("getAuthorization", new object[] {
                        in0,
                        in1,
                        in2}, this.getAuthorizationOperationCompleted, userState);
        }
        
        private void OngetAuthorizationOperationCompleted(object arg) {
            if ((this.getAuthorizationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAuthorizationCompleted(this, new getAuthorizationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://by-ws-ics-customermanagement/ws_customermanagement", ResponseNamespace="http://by-ws-ics-customermanagement/ws_customermanagement")]
        [return: System.Xml.Serialization.SoapElementAttribute("getCustomerInfoReturn")]
        public Customer getCustomerInfo(string in0, string[] in1) {
            object[] results = this.Invoke("getCustomerInfo", new object[] {
                        in0,
                        in1});
            return ((Customer)(results[0]));
        }
        
        /// <remarks/>
        public void getCustomerInfoAsync(string in0, string[] in1) {
            this.getCustomerInfoAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void getCustomerInfoAsync(string in0, string[] in1, object userState) {
            if ((this.getCustomerInfoOperationCompleted == null)) {
                this.getCustomerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomerInfoOperationCompleted);
            }
            this.InvokeAsync("getCustomerInfo", new object[] {
                        in0,
                        in1}, this.getCustomerInfoOperationCompleted, userState);
        }
        
        private void OngetCustomerInfoOperationCompleted(object arg) {
            if ((this.getCustomerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomerInfoCompleted(this, new getCustomerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://by-ws-ics-customermanagement/ws_customermanagement", ResponseNamespace="http://by-ws-ics-customermanagement/ws_customermanagement")]
        [return: System.Xml.Serialization.SoapElementAttribute("getCustomerInfoLDAPReturn")]
        public LDAPCustomer getCustomerInfoLDAP(string in0) {
            object[] results = this.Invoke("getCustomerInfoLDAP", new object[] {
                        in0});
            return ((LDAPCustomer)(results[0]));
        }
        
        /// <remarks/>
        public void getCustomerInfoLDAPAsync(string in0) {
            this.getCustomerInfoLDAPAsync(in0, null);
        }
        
        /// <remarks/>
        public void getCustomerInfoLDAPAsync(string in0, object userState) {
            if ((this.getCustomerInfoLDAPOperationCompleted == null)) {
                this.getCustomerInfoLDAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomerInfoLDAPOperationCompleted);
            }
            this.InvokeAsync("getCustomerInfoLDAP", new object[] {
                        in0}, this.getCustomerInfoLDAPOperationCompleted, userState);
        }
        
        private void OngetCustomerInfoLDAPOperationCompleted(object arg) {
            if ((this.getCustomerInfoLDAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomerInfoLDAPCompleted(this, new getCustomerInfoLDAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://by-ws-ics-customermanagement/ws_customermanagement", ResponseNamespace="http://by-ws-ics-customermanagement/ws_customermanagement")]
        [return: System.Xml.Serialization.SoapElementAttribute("updatePropertiesReturn")]
        public Customer updateProperties(Customer in0, string[] in1) {
            object[] results = this.Invoke("updateProperties", new object[] {
                        in0,
                        in1});
            return ((Customer)(results[0]));
        }
        
        /// <remarks/>
        public void updatePropertiesAsync(Customer in0, string[] in1) {
            this.updatePropertiesAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void updatePropertiesAsync(Customer in0, string[] in1, object userState) {
            if ((this.updatePropertiesOperationCompleted == null)) {
                this.updatePropertiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdatePropertiesOperationCompleted);
            }
            this.InvokeAsync("updateProperties", new object[] {
                        in0,
                        in1}, this.updatePropertiesOperationCompleted, userState);
        }
        
        private void OnupdatePropertiesOperationCompleted(object arg) {
            if ((this.updatePropertiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updatePropertiesCompleted(this, new updatePropertiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://by-ws-ics-customermanagement/ws_customermanagement", ResponseNamespace="http://by-ws-ics-customermanagement/ws_customermanagement")]
        [return: System.Xml.Serialization.SoapElementAttribute("updateRolePropertiesReturn")]
        public CustomerRole updateRoleProperties(CustomerRole in0, string[] in1) {
            object[] results = this.Invoke("updateRoleProperties", new object[] {
                        in0,
                        in1});
            return ((CustomerRole)(results[0]));
        }
        
        /// <remarks/>
        public void updateRolePropertiesAsync(CustomerRole in0, string[] in1) {
            this.updateRolePropertiesAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void updateRolePropertiesAsync(CustomerRole in0, string[] in1, object userState) {
            if ((this.updateRolePropertiesOperationCompleted == null)) {
                this.updateRolePropertiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateRolePropertiesOperationCompleted);
            }
            this.InvokeAsync("updateRoleProperties", new object[] {
                        in0,
                        in1}, this.updateRolePropertiesOperationCompleted, userState);
        }
        
        private void OnupdateRolePropertiesOperationCompleted(object arg) {
            if ((this.updateRolePropertiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateRolePropertiesCompleted(this, new updateRolePropertiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://by-ws-ics-customermanagement/ws_customermanagement", ResponseNamespace="http://by-ws-ics-customermanagement/ws_customermanagement")]
        [return: System.Xml.Serialization.SoapElementAttribute("getHRDataReturn")]
        public HRData getHRData(string in0) {
            object[] results = this.Invoke("getHRData", new object[] {
                        in0});
            return ((HRData)(results[0]));
        }
        
        /// <remarks/>
        public void getHRDataAsync(string in0) {
            this.getHRDataAsync(in0, null);
        }
        
        /// <remarks/>
        public void getHRDataAsync(string in0, object userState) {
            if ((this.getHRDataOperationCompleted == null)) {
                this.getHRDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHRDataOperationCompleted);
            }
            this.InvokeAsync("getHRData", new object[] {
                        in0}, this.getHRDataOperationCompleted, userState);
        }
        
        private void OngetHRDataOperationCompleted(object arg) {
            if ((this.getHRDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHRDataCompleted(this, new getHRDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://by-ws-ics-customermanagement/ws_customermanagement", ResponseNamespace="http://by-ws-ics-customermanagement/ws_customermanagement")]
        [return: System.Xml.Serialization.SoapElementAttribute("searchCustomersReturn")]
        public Customer[] searchCustomers(string in0, string[] in1) {
            object[] results = this.Invoke("searchCustomers", new object[] {
                        in0,
                        in1});
            return ((Customer[])(results[0]));
        }
        
        /// <remarks/>
        public void searchCustomersAsync(string in0, string[] in1) {
            this.searchCustomersAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void searchCustomersAsync(string in0, string[] in1, object userState) {
            if ((this.searchCustomersOperationCompleted == null)) {
                this.searchCustomersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchCustomersOperationCompleted);
            }
            this.InvokeAsync("searchCustomers", new object[] {
                        in0,
                        in1}, this.searchCustomersOperationCompleted, userState);
        }
        
        private void OnsearchCustomersOperationCompleted(object arg) {
            if ((this.searchCustomersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchCustomersCompleted(this, new searchCustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://by-ws-ics-customermanagement/ws_customermanagement", ResponseNamespace="http://by-ws-ics-customermanagement/ws_customermanagement")]
        [return: System.Xml.Serialization.SoapElementAttribute("createCustomerReturn")]
        public Customer createCustomer(string in0) {
            object[] results = this.Invoke("createCustomer", new object[] {
                        in0});
            return ((Customer)(results[0]));
        }
        
        /// <remarks/>
        public void createCustomerAsync(string in0) {
            this.createCustomerAsync(in0, null);
        }
        
        /// <remarks/>
        public void createCustomerAsync(string in0, object userState) {
            if ((this.createCustomerOperationCompleted == null)) {
                this.createCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateCustomerOperationCompleted);
            }
            this.InvokeAsync("createCustomer", new object[] {
                        in0}, this.createCustomerOperationCompleted, userState);
        }
        
        private void OncreateCustomerOperationCompleted(object arg) {
            if ((this.createCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createCustomerCompleted(this, new createCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://by-ws-ics-customermanagement/ws_customermanagement", ResponseNamespace="http://by-ws-ics-customermanagement/ws_customermanagement")]
        public void addRole(Customer in0, CustomerRole in1) {
            this.Invoke("addRole", new object[] {
                        in0,
                        in1});
        }
        
        /// <remarks/>
        public void addRoleAsync(Customer in0, CustomerRole in1) {
            this.addRoleAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void addRoleAsync(Customer in0, CustomerRole in1, object userState) {
            if ((this.addRoleOperationCompleted == null)) {
                this.addRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddRoleOperationCompleted);
            }
            this.InvokeAsync("addRole", new object[] {
                        in0,
                        in1}, this.addRoleOperationCompleted, userState);
        }
        
        private void OnaddRoleOperationCompleted(object arg) {
            if ((this.addRoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addRoleCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.service.customermanagement.ws.bayer.com")]
    public partial class Principal {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.service.customermanagement.ws.bayer.com")]
    public partial class HRData {
        
        private string addressField;
        
        private string birthnameField;
        
        private string companycodeNrField;
        
        private string companycodeTxtField;
        
        private string controllingareaNrField;
        
        private string controllingareaTxtField;
        
        private string costcenterField;
        
        private string costcenterLongField;
        
        private string cwidField;
        
        private string departmentNrField;
        
        private string departmentTxtField;
        
        private string divisionField;
        
        private string emailField;
        
        private string firstnameField;
        
        private string namePrefixField;
        
        private string nameSuffixField;
        
        private string orgUnitLongField;
        
        private string orgUnitShortField;
        
        private string personalIdField;
        
        private string personalIdOtherField;
        
        private string roomField;
        
        private string salutationField;
        
        private string sapSiteField;
        
        private string statusCustomerNrField;
        
        private string statusCustomerTxtField;
        
        private string statusEmploymentNrField;
        
        private string statusEmploymentTxtField;
        
        private string subdepartmentNrField;
        
        private string subdepartmentTxtField;
        
        private string surenameField;
        
        private string telefaxField;
        
        private string telephoneField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string birthname {
            get {
                return this.birthnameField;
            }
            set {
                this.birthnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string companycodeNr {
            get {
                return this.companycodeNrField;
            }
            set {
                this.companycodeNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string companycodeTxt {
            get {
                return this.companycodeTxtField;
            }
            set {
                this.companycodeTxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string controllingareaNr {
            get {
                return this.controllingareaNrField;
            }
            set {
                this.controllingareaNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string controllingareaTxt {
            get {
                return this.controllingareaTxtField;
            }
            set {
                this.controllingareaTxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string costcenter {
            get {
                return this.costcenterField;
            }
            set {
                this.costcenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string costcenterLong {
            get {
                return this.costcenterLongField;
            }
            set {
                this.costcenterLongField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cwid {
            get {
                return this.cwidField;
            }
            set {
                this.cwidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string departmentNr {
            get {
                return this.departmentNrField;
            }
            set {
                this.departmentNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string departmentTxt {
            get {
                return this.departmentTxtField;
            }
            set {
                this.departmentTxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string namePrefix {
            get {
                return this.namePrefixField;
            }
            set {
                this.namePrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nameSuffix {
            get {
                return this.nameSuffixField;
            }
            set {
                this.nameSuffixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orgUnitLong {
            get {
                return this.orgUnitLongField;
            }
            set {
                this.orgUnitLongField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string orgUnitShort {
            get {
                return this.orgUnitShortField;
            }
            set {
                this.orgUnitShortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string personalId {
            get {
                return this.personalIdField;
            }
            set {
                this.personalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string personalIdOther {
            get {
                return this.personalIdOtherField;
            }
            set {
                this.personalIdOtherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sapSite {
            get {
                return this.sapSiteField;
            }
            set {
                this.sapSiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusCustomerNr {
            get {
                return this.statusCustomerNrField;
            }
            set {
                this.statusCustomerNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusCustomerTxt {
            get {
                return this.statusCustomerTxtField;
            }
            set {
                this.statusCustomerTxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusEmploymentNr {
            get {
                return this.statusEmploymentNrField;
            }
            set {
                this.statusEmploymentNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusEmploymentTxt {
            get {
                return this.statusEmploymentTxtField;
            }
            set {
                this.statusEmploymentTxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string subdepartmentNr {
            get {
                return this.subdepartmentNrField;
            }
            set {
                this.subdepartmentNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string subdepartmentTxt {
            get {
                return this.subdepartmentTxtField;
            }
            set {
                this.subdepartmentTxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string surename {
            get {
                return this.surenameField;
            }
            set {
                this.surenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string telefax {
            get {
                return this.telefaxField;
            }
            set {
                this.telefaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.service.customermanagement.ws.bayer.com")]
    public partial class LDAPCustomer {
        
        private string buildingField;
        
        private string cityField;
        
        private string companyField;
        
        private string countryField;
        
        private string cwidField;
        
        private string departmentField;
        
        private string divisionField;
        
        private string emailField;
        
        private string executiveField;
        
        private string faxField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string personalIdField;
        
        private string phoneField;
        
        private string positionField;
        
        private string salutationField;
        
        private string siteField;
        
        private string streetField;
        
        private string titleField;
        
        private string zipCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cwid {
            get {
                return this.cwidField;
            }
            set {
                this.cwidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string executive {
            get {
                return this.executiveField;
            }
            set {
                this.executiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string personalId {
            get {
                return this.personalIdField;
            }
            set {
                this.personalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.service.customermanagement.ws.bayer.com")]
    public partial class RoleProperty {
        
        private string applicationNameField;
        
        private string nameField;
        
        private string sizeField;
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string applicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.service.customermanagement.ws.bayer.com")]
    public partial class CustomerRole {
        
        private string applicationNameField;
        
        private string descrField;
        
        private string nameField;
        
        private RoleProperty[] propertiesField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string applicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public RoleProperty[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.service.customermanagement.ws.bayer.com")]
    public partial class CustomerProperty {
        
        private string applicationNameField;
        
        private string nameField;
        
        private string sizeField;
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string applicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.service.customermanagement.ws.bayer.com")]
    public partial class CustomerCostcenter {
        
        private string applicationNameField;
        
        private string changeableField;
        
        private string remarkField;
        
        private string sapObjectField;
        
        private string sapTypeField;
        
        private string statusField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string applicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string changeable {
            get {
                return this.changeableField;
            }
            set {
                this.changeableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sapObject {
            get {
                return this.sapObjectField;
            }
            set {
                this.sapObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sapType {
            get {
                return this.sapTypeField;
            }
            set {
                this.sapTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.service.customermanagement.ws.bayer.com")]
    public partial class Customer {
        
        private string administrationField;
        
        private string buildingField;
        
        private string cityField;
        
        private string codeField;
        
        private string companyField;
        
        private CustomerCostcenter[] costcentersField;
        
        private string countryField;
        
        private string cwidField;
        
        private string departmentField;
        
        private string divisionField;
        
        private string emailField;
        
        private string executiveField;
        
        private string faxField;
        
        private string firstnameField;
        
        private long idField;
        
        private string lastUpdateField;
        
        private string lastnameField;
        
        private string notesEmailField;
        
        private string oldCustomerIdField;
        
        private long personalIdField;
        
        private string phoneField;
        
        private string positionField;
        
        private string positionDescField;
        
        private string postOfficeBoxField;
        
        private Principal[] principalsField;
        
        private CustomerProperty[] propertiesField;
        
        private string registrationDateField;
        
        private string remarkField;
        
        private CustomerRole[] rolesField;
        
        private string salutationField;
        
        private string siteField;
        
        private string streetField;
        
        private string titleField;
        
        private string workingStatusField;
        
        private string zipCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string administration {
            get {
                return this.administrationField;
            }
            set {
                this.administrationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public CustomerCostcenter[] costcenters {
            get {
                return this.costcentersField;
            }
            set {
                this.costcentersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cwid {
            get {
                return this.cwidField;
            }
            set {
                this.cwidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string executive {
            get {
                return this.executiveField;
            }
            set {
                this.executiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string lastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string notesEmail {
            get {
                return this.notesEmailField;
            }
            set {
                this.notesEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string oldCustomerId {
            get {
                return this.oldCustomerIdField;
            }
            set {
                this.oldCustomerIdField = value;
            }
        }
        
        /// <remarks/>
        public long personalId {
            get {
                return this.personalIdField;
            }
            set {
                this.personalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string positionDesc {
            get {
                return this.positionDescField;
            }
            set {
                this.positionDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string postOfficeBox {
            get {
                return this.postOfficeBoxField;
            }
            set {
                this.postOfficeBoxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Principal[] principals {
            get {
                return this.principalsField;
            }
            set {
                this.principalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public CustomerProperty[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string registrationDate {
            get {
                return this.registrationDateField;
            }
            set {
                this.registrationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public CustomerRole[] roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string workingStatus {
            get {
                return this.workingStatusField;
            }
            set {
                this.workingStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getVersionCompletedEventHandler(object sender, getVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getAuthenticationCompletedEventHandler(object sender, getAuthenticationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAuthenticationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAuthenticationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Principal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Principal[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getAuthorizationCompletedEventHandler(object sender, getAuthorizationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAuthorizationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAuthorizationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Customer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Customer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getCustomerInfoCompletedEventHandler(object sender, getCustomerInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustomerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Customer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Customer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getCustomerInfoLDAPCompletedEventHandler(object sender, getCustomerInfoLDAPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomerInfoLDAPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustomerInfoLDAPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LDAPCustomer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LDAPCustomer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void updatePropertiesCompletedEventHandler(object sender, updatePropertiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updatePropertiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updatePropertiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Customer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Customer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void updateRolePropertiesCompletedEventHandler(object sender, updateRolePropertiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateRolePropertiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateRolePropertiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerRole Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerRole)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getHRDataCompletedEventHandler(object sender, getHRDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHRDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHRDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HRData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HRData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void searchCustomersCompletedEventHandler(object sender, searchCustomersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Customer[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Customer[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void createCustomerCompletedEventHandler(object sender, createCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Customer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Customer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void addRoleCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591